### ISSUE TITLE
Any support for Teal 3?

### ISSUE THREAD

**Issue by alifmufthi91** [bloxbean/algodea#24]

**Comment by satran004** [comment]
Teal 3  support will be added in the next release. But as of now, there is no release date yet.

**Comment by satran004** [comment]
Added TEAL v3 support. 
v0.5.0-beta is now available for download from GitHub. You can manually download the binary and install for now.

Not yet available in IntelliJ marketplace. If no major issue found, this release will be pushed to IntelliJ marketplace within a week.

**Comment by iskysun96** [comment]
has TEAL v3 support been pushed to the marketplace yet? Also, do we need to uninstall and reinstall the updated algoDea?

**Comment by satran004** [comment]
TEAL v3 support will be pushed by end of this week. You may need to uninstall first and then install the update. I will add a note here once it's done.
