### ISSUE TITLE
IntelliJ dialog box too big for window - Not allowing to set Foreign Assets for AppCall

### ISSUE THREAD

**Issue by GuidoDipietro** [bloxbean/algodea#33]
I can't set Foreign Assets for an Application Call transaction.

![image](https://user-images.githubusercontent.com/48221146/144334322-429570b7-fbfa-4dcf-9651-b8cb158f7dde.png)

Possible workaround?
Thanks!

PS: This tool is awesome. I love using AlgoDEA!

**Comment by satran004** [comment]
@GuidoDipietro Did you try to change the screen resolution ? 

There is a min size set for this panel.  

I will try to add a scrollbar to this screen in the next iteration.

thanks.

**Comment by GuidoDipietro** [comment]
I wanted to see if there was any possible workaround without changing the resolution, but I think I'll go with that for now.

Thanks 👍
