### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by GuidoDipietro** [bloxbean/algodea#35]
Funny issue now, but there are some typos in the plugin (v0.8.0)

The approval program for a Stateful TEAL project is named `approval_progam.teal` (notice the missing `r`).

And the other one found was the `Destory` button for the destroy ASA dialog box (notice swapped `o` and `r`).

Thanks again :)

**Comment by satran004** [comment]
Not sure why I never noticed that. My bad :(

Thanks for reporting this issue.
