### ISSUE TITLE
Support ASA in Stateless Smart Contract Transaction with Logic Sig

### ISSUE THREAD

**Issue by cusma** [bloxbean/algodea#4]
**Proposal**
Currently only ALGO amount is available for Transaction with Logic Sig. Would be very useful supporting any ASA amount also.

**Comment by satran004** [comment]
Thanks. I will add this in the next release.

**Comment by satran004** [comment]
@cusma, a new release 0.3.2 with this change is now available here https://github.com/bloxbean/algodea/releases/tag/v0.3.2
You can manually download the zip and try it.
This release will be available in IntelliJ's official marketplace in few days.

Changes:
- ASA support has been added to the Send Transaction (Logic Sig) UI
- A new menu option has been added for Opt-In Asset transaction using Logic Sig. (Both for contract account & delegated signature mode).

###  Screenshots:

![menu](https://user-images.githubusercontent.com/35016438/108595624-e4d25400-73bb-11eb-8f73-006edfbb99d8.png)


![ASA Transfer using LogicSig](https://user-images.githubusercontent.com/35016438/108595627-ea2f9e80-73bb-11eb-963b-660acf62c5a9.png)


![Opt-In Asset Using Logic Sig](https://user-images.githubusercontent.com/35016438/108595631-ef8ce900-73bb-11eb-83d5-b2a9fccbb210.png)

**Comment by cusma** [comment]
Great! Very useful feature! I'll try it right away.
